const fs = require('fs');
let src = fs.readFileSync('C:/Users/Jepii/Desktop/la-pausa-mundial/public/js/fotos.js', 'utf8');

const upd = [
  ["'Gabriel Avalos': _L + '789453-t.webp'",      "'Gabriel Avalos': _L + 'Gabriel_Ávalos.PNG',\n  'Gabriel Ávalos': _L + 'Gabriel_Ávalos.PNG'"],
  ["'Gustavo Caballero': _L + '988656-t.webp'",   "'Gustavo Caballero': _L + 'Gustavo_Caballero.PNG'"],
  ["'Alex Arce': _L + '1167312-t.webp'",          "'Alex Arce': _L + 'Alex_Arce.PNG'"],
  ["'Damian Bobadilla': _L + '1015261-t.webp'",   "'Damian Bobadilla': _L + 'Damian_Bobadilla.PNG'"],
  ["'Gustavo Velazquez': _L + '851495-t.webp'",   "'Gustavo Velazquez': _L + 'Gustavo_Velázquez.PNG',\n  'Gustavo Velázquez': _L + 'Gustavo_Velázquez.PNG'"],
  ["'Alexandro Maidana': _L + '1546739-t.webp'",  "'Alexandro Maidana': _L + 'Alexandro_Maidana.PNG'"],
  ["'Junior Alonso': _L + '333275-t.webp'",       "'Junior Alonso': _L + 'Junior_Alonso.PNG'"],
  ["'Orlando Gill': _L + '991709-t.webp'",        "'Orlando Gill': _L + 'Orlando_Gill.PNG'"],
  ["'Antonio Sanabria': _L + '333261-t.webp'",    "'Antonio Sanabria': _L + 'Antonio_Sanabria.png'"],
  ["'Matias Galarza': _L + '1086924-t.webp'",     "'Matias Galarza': _L + 'Matías_Galarza.png',\n  'Matías Galarza': _L + 'Matías_Galarza.png'"],
  ["'Fabian Balbuena': _L + '339447-t.webp'",     "'Fabian Balbuena': _L + 'Fabián_Balbuena.png',\n  'Fabián Balbuena': _L + 'Fabián_Balbuena.png'"],
  ["'Gaston Olveira': _L + '339135-t.webp'",      "'Gaston Olveira': _L + 'Gaston_Olveira.png'"],
  ["'Ante Suto': _L + '997227-t.webp'",           "'Ante Suto': _L + 'Ante_Šuto.png',\n  'Ante Šuto': _L + 'Ante_Šuto.png'"],
  ["'Deni Juric': _L + '855970-t.webp'",          "'Deni Juric': _L + 'Deni_Jurić.png',\n  'Deni Jurić': _L + 'Deni_Jurić.png'"],
  ["'Paul Okon-Engstler': _L + '1411105-t.webp'", "'Paul Okon-Engstler': _L + 'Paul_Okon-Engstler.png'"],
  ["'Patrick Yazbek': _L + '1106270-t.webp'",     "'Patrick Yazbek': _L + 'Patrick_Yazbek.png'"],
  ["'Milos Degenek': _L + '155961-t.webp'",       "'Milos Degenek': _L + 'Milos_Degenek.png'"],
  ["'Cameron Burgess': _L + '358084-t.webp'",     "'Cameron Burgess': _L + 'Cameron_Burgess.png'"],
  ["'Patrick Beach': _L + '1177240-t.webp'",      "'Patrick Beach': _L + 'Patrick_Beach.png'"],
  ["'Ajdin Hrustic': _L + '788284-t.webp'",       "'Ajdin Hrustic': _L + 'Ajdin_Hrustic.PNG'"],
  ["'Connor Metcalfe': _L + '888854-t.webp'",     "'Connor Metcalfe': _L + 'Connor_Metcalfe.PNG'"],
  ["\"'Aiden O'Neill': _L + '847938-t.webp'\"",   "\"'Aiden O'Neill': _L + 'Aiden_ONeill.PNG'\""],
  ["'Riley McGree': _L + '835998-t.webp'",        "'Riley McGree': _L + 'Riley_McGree.PNG'"],
  ["'Aziz Behich': _L + '576220-t.webp'",         "'Aziz Behich': _L + 'Aziz_Behich.PNG'"],
  ["'Lucas Herrington': _L + '1646783-t.webp'",   "'Lucas Herrington': _L + 'Lucas_Herrington.PNG'"],
  ["'Jason Geria': _L + '303258-t.webp'",         "'Jason Geria': _L + 'Jason_Geria.PNG'"],
  ["'Jacob Italiano': _L + '907217-t.webp'",      "'Jacob Italiano': _L + 'Jacob_Italiano.PNG'"],
  ["'Kye Rowles': _L + '822572-t.webp'",          "'Kye Rowles': _L + 'Kye_Rowles.PNG'"],
  ["'Paul Izzo': _L + '155925-t.webp'",           "'Paul Izzo': _L + 'Paul_Izzo.PNG'"],
  ["'Nishan Velupillay': _L + '1118467-t.webp'",  "'Nishan Velupillay': _L + 'Nishan_Velupillay.PNG'"],
  ["'Kai Trewin': _L + '991364-t.webp'",          "'Kai Trewin': _L + 'Kai_Trewin.PNG'"],
  ["'Alex Robertson': _L + '1067119-t.webp'",     "'Alex Robertson': _L + 'Alex_Robertson.PNG'"],
  ["'Angelo Preciado': _L + '881844-t.webp'",     "'Angelo Preciado': _L + 'Angelo_Preciado.PNG'"],
  ["'Yaimar Medina': _L + '1106546-t.webp'",      "'Yaimar Medina': _L + 'Yaimar_Medina.PNG'"],
  ["'Felix Torres': _L + '881848-t.webp'",        "'Felix Torres': _L + 'Felix_Torres.PNG'"],
  ["'Jackson Porozo': _L + 'Jackson_Porozo.png'", "'Jackson Porozo': _L + 'Jackson_Porozo.PNG'"],
  ["'Alan Franco': _L + 'Alan_Franco.webp'",      "'Alan Franco': _L + 'Alan_Franco.PNG'"],
  ["'John Yeboah': _L + '879802-t.webp'",         "'John Yeboah': _L + 'John_Yeboah.PNG'"],
  ["'Jordy Alcivar': _L + '925740-t.webp'",       "'Jordy Alcivar': _L + 'Jordy_Alcivar.PNG'"],
  ["'Alan Minda': _L + '1122552-t.webp'",         "'Alan Minda': _L + 'Alan_Minda.PNG'"],
  ["'John Mercado': _L + '1002514-t.webp'",       "'John Mercado': _L + 'John_Mercado.png'"],
  ["'Janner Corozo': _L + '868275-t.webp'",       "'Janner Corozo': _L + 'Janner_Corozo.PNG'"],
  ["'Anthony Valencia': _L + '1020197-t.webp'",   "'Anthony Valencia': _L + 'Anthony_Valencia.png'"],
  ["'Bryan Ramirez': _L + '1459658-t.webp'",      "'Bryan Ramirez': _L + 'Bryan_Ramírez.png',\n  'Bryan Ramírez': _L + 'Bryan_Ramírez.png'"],
  ["'Jordy Caicedo': _L + '804770-t.webp'",       "'Jordy Caicedo': _L + 'Jordy_Caicedo.png'"],
  ["'Kevin Rodriguez': _L + '1431770-t.webp'",    "'Kevin Rodriguez': _L + 'Kevin_Rodríguez.png',\n  'Kevin Rodríguez': _L + 'Kevin_Rodríguez.png'"],
  ["'Denil Castillo': _L + '1145126-t.webp'",     "'Denil Castillo': _L + 'Denil_Castillo.png'"],
  ["'Leo Realpe': _L + '977676-t.webp'",          "'Leo Realpe': _L + 'Leo_Realpe.png'"],
  ["'Jose Andres Hurtado': _L + '987589-t.webp'", "'Jose Andres Hurtado': _L + 'Jose_Andrés_Hurtado.png',\n  'Jose Andrés Hurtado': _L + 'Jose_Andrés_Hurtado.png'"],
  ["'Hernan Galindez': _L + '588618-t.webp'",     "'Hernan Galindez': _L + 'Hernan_Galindez.PNG'"],
  ["'Gonzalo Valle': _L + '925484-t.webp'",       "'Gonzalo Valle': _L + 'Gonzalo_Valle.PNG'"],
  ["'David Cabezas': _L + '886492-t.webp'",       "'David Cabezas': _L + 'David_Cabezas.png'"],
  ["'Andres Cubas': _L + '546416-t.webp'",        "'Andres Cubas': _L + 'Andrés_Cubas.png',\n  'Andrés Cubas': _L + 'Andrés_Cubas.png'"],
  ["'Tomoki Hayakawa': _L + '1100230-t.webp'",    "'Tomoki Hayakawa': _L + 'Tomoki_Hayakawa.PNG'"],
  ["'Elias Legendre Quinonez': _L + 'Elias_Legendre.png'", "'Elias Legendre Quinonez': _L + 'Elias_Legendre_Quiñónez.PNG',\n  'Elias Legendre Quiñónez': _L + 'Elias_Legendre_Quiñónez.PNG'"],
  ["'Tsuyoshi Watanabe': _L + '942213-t.webp'",   "'Tsuyoshi Watanabe': _L + 'Tsuyoshi_Watanabe.PNG'"],
  ["'Daiki Hashioka': _L + '897334-t.webp'",      "'Daiki Hashioka': _L + 'Daiki_Hashioka.png'"],
  ["'Shogo Taniguchi': _L + '386958-t.webp'",     "'Shogo Taniguchi': _L + 'Shogo_Taniguchi.PNG'"],
  ["'Joel Chima Fujita': _L + '1002461-t.webp'",  "'Joel Chima Fujita': _L + 'Joel_Chima_Fujita.PNG'"],
  ["'Ayumu Seko': _L + 'Ayumu_Seko.png'",         "'Ayumu Seko': _L + 'Ayumu_Seko.PNG'"],
  ["'Junya Ito': _L + '783278-t.webp'",           "'Junya Ito': _L + 'Junya_Ito.PNG'"],
  ["'Shuto Machino': _L + '925910-t.webp'",       "'Shuto Machino': _L + 'Shuto_Machino.PNG'"],
  ["'Kento Shiogai': _L + '1499696-t.webp'",      "'Kento Shiogai': _L + 'Kento_Shiogai.PNG'"],
  ["'Keisuke Goto': _L + '1391315-t.webp'",       "'Keisuke Goto': _L + 'Keisuke_Goto.png'"],
  ["'Koki Ogawa': _L + '831860-t.webp'",          "'Koki Ogawa': _L + 'Koki_Ogawa.png'"],
  ["'Ryunosuke Sato': _L + '1476200-t.webp'",     "'Ryunosuke Sato': _L + 'Ryunosuke_Sato.png'"],
  ["'Kodai Sano': _L + '1184054-t.webp'",         "'Kodai Sano': _L + 'Kodai_Sano.png'"],
  ["'Junnosuke Suzuki': _L + '1171902-t.webp'",   "'Junnosuke Suzuki': _L + 'Junnosuke_Suzuki.png'"],
  ["'Noel Tornqvist': _L + '1014583-t.webp'",     "'Noel Tornqvist': _L + 'Noel_Tornqvist.png'"],
  ["'Eric Smith': _L + '542038-t.webp'",          "'Eric Smith': _L + 'Eric_Smith.PNG'"],
  ["'Benjamin Nygren': _L + '918517-t.webp'",     "'Benjamin Nygren': _L + 'Benjamin_Nygren.png'"],
  ["'Taha Ali': _L + '1022820-t.webp'",           "'Taha Ali': _L + 'Taha_Ali.PNG'"],
  ["'Gustav Lundgren': _L + '1185629-t.webp'",    "'Gustav Lundgren': _L + 'Gustav_Lundgren.PNG'"],
  ["'Herman Johansson': _L + '1099794-t.webp'",   "'Herman Johansson': _L + 'Herman_Johansson.png'"],
  ["'Elliot Stroud': _L + '1383695-t.webp'",      "'Elliot Stroud': _L + 'Elliot_Stroud.png'"],
  ["'Kristoffer Nordfeldt': _L + '22596-t.webp'", "'Kristoffer Nordfeldt': _L + 'Kristoffer_Nordfeldt.png'"],
  ["'Noureddine Farhati': _L + '1013956-t.webp'", "'Noureddine Farhati': _L + 'Noureddine_Farhati.png'"],
  ["'Sabri Ben Hessen': _L + '359312-t.webp'",    "'Sabri Ben Hessen': _L + 'Sabri_Ben_Hessen.PNG'"],
  ["'Alaa Ghram': _L + '1011994-t.webp'",         "'Alaa Ghram': _L + 'Alaa_Ghram.PNG'"],
  ["'Moutaz Neffati': _L + '1391526-t.webp'",     "'Moutaz Neffati': _L + 'Moutaz_Neffati.PNG'"],
  ["'Ghaith Zaalouni': _L + '1606544-t.webp'",    "'Ghaith Zaalouni': _L + 'Ghaith_Zaalouni.PNG'"],
  ["'Rani Khedira': _L + '149479-t.webp'",        "'Rani Khedira': _L + 'Rani_Khedira.PNG'"],
  ["'Mohamed Belhadj Mahmoud': _L + '1008597-t.webp'", "'Mohamed Belhadj Mahmoud': _L + 'Mohamed_Belhadj_Mahmoud.png'"],
  ["'Khalil Ayari': _L + '1606568-t.webp'",       "'Khalil Ayari': _L + 'Khalil_Ayari.PNG'"],
  ["'Hazem Mastouri': _L + '1991585-t.webp'",     "'Hazem Mastouri': _L + 'Hazem_Mastouri.png'"],
  ["'Anisse Saidi': _L + '1854324-t.webp'",       "'Anisse Saidi': _L + 'Anisse_Saidi.PNG'"],
  ["'Mortadha Ben Ouanes': _L + '919225-t.webp'", "'Mortadha Ben Ouanes': _L + 'Mortadha_Ben_Ouanes.PNG'"],
  ["'Rayan Elloumi': _L + '1872950-t.webp'",      "'Rayan Elloumi': _L + 'Rayan_Elloumi.png'"],
  ["'Omar Ben Ali': _L + '1996692-t.webp'",       "'Omar Ben Ali': _L + 'Omar_Ben_Ali.png'"],
  ["'Firas Chaouat': _L + '919198-t.webp'",       "'Firas Chaouat': _L + 'Firas_Chaouat.png'"],
  ["'Adem Arous': _L + '2018238-t.webp'",         "'Adem Arous': _L + 'Adem_Arous.png'"],
  ["'Omar Rekik': _L + '976251-t.webp'",          "'Omar Rekik': _L + 'Omar_Rekik.png'"],
  ["'Yan Valery': _L + '826202-t.webp'",          "'Yan Valery': _L + 'Yan_Valery.png'"],
  ["'Gervane Kastaneer': _L + '798178-t.webp'",   "'Gervane Kastaneer': _L + 'Gervane_Kastaneer.PNG'"],
  ["'Brandley Kuwas': _L + '252885-t.webp'",      "'Brandley Kuwas': _L + 'Brandley_Kuwas.PNG'"],
  ["'Kenji Gorre': _L + '796142-t.webp'",         "'Kenji Gorre': _L + 'Kenji_Gorre.PNG'"],
  ["'Jearl Margaritha': _L + '1036004-t.webp'",   "'Jearl Margaritha': _L + 'Jearl_Margaritha.png'"],
  ["'Jeremy Antonisse': _L + '1092638-t.webp'",   "'Jeremy Antonisse': _L + 'Jeremy_Antonisse.PNG'"],
  ["'Godfried Roemeratoe': _L + '825849-t.webp'", "'Godfried Roemeratoe': _L + 'Godfried_Roemeratoe.PNG'"],
  ["'Kevin Felida': _L + '896215-t.webp'",        "'Kevin Felida': _L + 'Kevin_Felida.PNG'"],
  ["'Juninho Bacuna': _L + '788971-t.webp'",      "'Juninho Bacuna': _L + 'Juninho_Bacuna.PNG'"],
  ["'Roshon van Eijma': _L + '925930-t.webp'",    "'Roshon van Eijma': _L + 'Roshon_Van_Eijma.PNG',\n  'Roshon Van Eijma': _L + 'Roshon_Van_Eijma.PNG'"],
  ["'Jurien Gaari': _L + '884944-t.webp'",        "'Jurien Gaari': _L + 'Jurien_Gaari.PNG'"],
  ["'Livano Comenencia': _L + '1136642-t.webp'",  "'Livano Comenencia': _L + 'Livano_Comenencia.PNG'"],
  ["'Joshua Brenet': _L + '296438-t.webp'",       "'Joshua Brenet': _L + 'Joshua_Brenet.PNG'"],
  ["'Shurandy Sambo': _L + '916926-t.webp'",      "'Shurandy Sambo': _L + 'Shurandy_Sambo.png'"],
  ["'Tyrick Bodak': _L + '1049270-t.webp'",       "'Tyrick Bodak': _L + 'Tyrick_Bodak.PNG'"],
  ["'Trevor Doornbusch': _L + '895013-t.webp'",   "'Trevor Doornbusch': _L + 'Trevor_Doornbusch.PNG'"],
  ["'Deveron Fonville': _L + '1177177-t.webp'",   "'Deveron Fonville': _L + 'Deveron_Fonville.png'"],
  ["'Sherel Floranus': _L + '803021-t.webp'",     "'Sherel Floranus': _L + 'Sherel_Floranus.png'"],
  ["'Jean Michael Seri': _L + '305282-t.webp'",   "'Jean Michael Seri': _L + 'Jean_Michael_Seri.png'"],
  ["'Seko Fofana': _L + '191188-t.webp'",         "'Seko Fofana': _L + 'Seko_Fofana.png'"],
  ["'Ghislain Konan': _L + '831781-t.webp'",      "'Ghislain Konan': _L + 'Ghislain_Konan.png'"],
  ["'Alban Lafont': _L + '826201-t.webp'",        "'Alban Lafont': _L + 'Alban_Lafont.png'"],
  ["'Yahia Fofana': _L + '877977-t.webp'",        "'Yahia Fofana': _L + 'Yahia_Fofana.png'"],
  ["'Parfait Guiagon': _L + '1030459-t.webp'",    "'Parfait Guiagon': _L + 'Parfait_Guiagon.PNG'"],
  ["'Oliver Baumann': _L + '40244-t.webp'",       "'Oliver Baumann': _L + 'Oliver_Baumann.PNG'"],
  ["'Atakan Karazor': _L + '801030-t.webp'",      "'Atakan Karazor': _L + 'Atakan_Karazor.PNG'"],
  ["'Ahmetcan Kaplan': _L + '1064177-t.webp'",    "'Ahmetcan Kaplan': _L + 'Ahmetcan_Kaplan.PNG'"],
  ["'Finn Dahmen': _L + '822564-t.webp'",         "'Finn Dahmen': _L + 'Finn_Dahmen.png'"],
  ["'Yunus Akgun': _L + '857738-t.webp'",         "'Yunus Akgun': _L + 'Yunus_Akgün.png',\n  'Yunus Akgün': _L + 'Yunus_Akgün.png'"],
  ["'Kaan Ayhan': _L + '138152-t.webp'",          "'Kaan Ayhan': _L + 'Kaan_Ayhan.png'"],
  ["'Salih Ozcan': _L + '795005-t.webp'",         "'Salih Ozcan': _L + 'Salih_Özcan.png',\n  'Salih Özcan': _L + 'Salih_Özcan.png'"],
  ["'Samet Akaydin': _L + '863600-t.webp'",       "'Samet Akaydin': _L + 'Samet_Akaydin.png'"],
  ["'Mert Gunok': _L + '39573-t.webp'",           "'Mert Gunok': _L + 'Mert_Gunok.png'"],
  ["'Mustafa Eskihellac': _L + '899069-t.webp'",  "'Mustafa Eskihellac': _L + 'Mustafa_Eskihellaç.PNG',\n  'Mustafa Eskihellaç': _L + 'Mustafa_Eskihellaç.PNG'"],
  ["'Eren Elmali': _L + '981483-t.webp'",         "'Eren Elmali': _L + 'Eren_Elmalı.PNG',\n  'Eren Elmalı': _L + 'Eren_Elmalı.PNG'"],
  ["'Muhammed Sengezer': _L + '827418-t.webp'",   "'Muhammed Sengezer': _L + 'Muhammed_Şengezer.PNG',\n  'Muhammed Şengezer': _L + 'Muhammed_Şengezer.PNG'"],
];

let ok = 0, fail = 0;
for (const [from, to] of upd) {
  if (src.includes(from)) { src = src.replace(from, to); ok++; }
  else { console.log('FAIL:', from.substring(0, 55)); fail++; }
}

// Mohamed Amine Ben Hamida — regex
const m = src.match(/'Mohamed Amine Ben Hamida': _L \+ '[^']+'/);
if (m) { src = src.replace(m[0], "'Mohamed Amine Ben Hamida': _L + 'Mohamed_Amine_Ben_Hamida.png'"); ok++; }
else { console.log('FAIL: Mohamed Amine Ben Hamida'); fail++; }

fs.writeFileSync('C:/Users/Jepii/Desktop/la-pausa-mundial/public/js/fotos.js', src, 'utf8');
console.log('OK:', ok, '| Fail:', fail);
